open-edge-platform/edge-manageability-framework

README.md
=> chore: unify platform service naming

README.md
Fix troubleshooting link in README
N/A
N/A
=> fix: troubleshooting link

argocd/applications/configs/cluster-manager.yaml, argocd/applications/templates/cluster-manager.yaml
enable metrics in template controller
=> feat: enabled template controller metrics

argocd/applications/templates/cluster-connect-gateway.yaml
Bump CCG version to 1.0.6.  This version fixes a labeling issue that prevents the CCG Helm chart from being upgraded to a new version.
Tested in Coder env.
=> bump CCG to 1.0.6

argocd/applications/templates/web-ui-admin.yaml
Update copyright message displayed in UI
=> [ITEP-27300] - update year to 2025

README.md
=> Set of edits to repo descriptions in README

argocd/applications/configs/fleet-controller.yaml, argocd/applications/templates/fleet-controller.yaml, argocd/applications/templates/fleet-crd.yaml
Reverts open-edge-platform/edge-manageability-framework#169
=> Revert "Upgrade fleet to 0.10.4"

argocd/applications/configs/infra-onboarding.yaml, argocd/applications/templates/infra-onboarding.yaml
Pick up changes from https://github.com/open-edge-platform/infra-charts/pull/34.
- Update infra-onboarding to 1.29.8
- TinkerActions to 1.17.2
https://github.com/open-edge-platform/infra-onboarding/pull/55 - Responsible for bump in OM version & DKAM version has been verified in 3 environments(onprem/onprem with OT/coder) by patching running OM image with a locally built image. 
Bare Metal EN provisioned in all cases to verify smooth provisioning.
=> Update infra-onboarding & tinkerActions

terraform/orchestrator/terraform.tfvars, terraform/orchestrator/variables.tf
`latest-main` is correct and `latest-main-dev` is not
=> Update default tag for deploying On-Prem Orchestrator

.github/CODEOWNERS, mage/Magefile.go, mage/edge_cluster.go, mage/tenant_utils.go
- `mage deploy:edgeCluster` was broken due to recent changes to ENiC. Added registering ENiC to allow cluster creation
- Added some app orch members to `edge_cluster` file as codeowners
- Removed onboarding user since registering host (EniC) uses api user. And api user works for everything else.
=> Update edgeCluster with ENiC NIO

design-proposals/app-orch-dp-import.md
Proposal for importing deployment packages from repositories by using the GUI to allow the user to specify the URL of a repository, and having the application catalog service clone the repo and extract the DP
No.
Markdownlint.
=> proposal for importing deployment packages from repositories

terraform/orchestrator/main.tf
Cloud init sets a flag when it finishes installing the packages. This check is important due to some race condition. In our current setup this was only checked when not using locally built artifacts. We should also check when using locally built artifacts because the installer depends on the packages installed during the cloud init phase.
N/A
Locally
=> Wait for cloud init to finish

mage/publish.go
- Use shared functions in build process
- Remove unused tags attached to published artifacts
=> Clean up artifact build to use common functions

mage/edge_cluster.go
=> Add provisioning enic step to deploy enic cluster target

README.md
=> fixing more URLs in readme

.github/workflows/virtual-integration.yml
Disables flaky sre tests to unblock others while we debug the issue.
=> fix: disable-sre-tests

README.md
To see how the project grows via ⭐ ⭐ ⭐ 
Live view generated from https://www.star-history.com/#open-edge-platform/edge-manageability-framework&Date
Renders like this:
**You must be on a public network to view the live markdown preview due to GitHub API limits on a private network.**
=> docs: add star history chart to main README.md ⭐ 📈 

argocd/applications/configs/infra-managers.yaml
Update OSProfile to v0.4.1.
https://github.com/open-edge-platform/infra-core/pull/118
=> Update OSProfiles to 0.4.1

.github/workflows/auto-approve-merge.yml
=> chore: use gl cli for auto merge

argocd/applications/templates/cluster-manager.yaml
Bump cluster manager from dev to release version.
None.
VIP pipeline
=> chore: update version to 2.1.1 for cluster-manager

README.md, design-proposals/co-cli.md, pod-configs/README.md, pod-configs/module/ec2log/README.md, pod-configs/orchestrator/vpc/README.md
Fix markdown errors.
N/A
Locally and CI
=> Fix markdown linter issues

.tool-versions, mage/Magefile.go
This PR removes the need to have installed python installed as an asdf plugin.
N/A
On CI and locally.
=> Remove python dependency

.github/workflows/virtual-integration.yml
=> fix: remove duplicated license check which is already part of premerge tasks

argocd/applications/configs/infra-external.yaml
Disabling AMT helm chart for now to unblock the pipeline and will re-enable it later once we have fix.
=> Disable DMT 

.github/CODEOWNERS
Update the design proposals code owners.
n/a
CI
=> Adding approvers for design proposals

.github/workflows/virtual-integration.yml
Reverts open-edge-platform/edge-manageability-framework#375
=> Revert "chore: only run deploy-kind / deploy-onprem when change does not include new-installer"

.github/CODEOWNERS
Updating codeowners file for the UI components
=> Updating UI team members

argocd/applications/configs/infra-onboarding.yaml
1. [fix: Update provisioning status when host has been deauthorized (](https://github.com/open-edge-platform/infra-onboarding/commit/37da87c1dd0a06a2904d8e399b947e53d27ce692)https://github.com/open-edge-platform/infra-onboarding/pull/70[)](https://github.com/open-edge-platform/infra-onboarding/commit/37da87c1dd0a06a2904d8e399b947e53d27ce692)
2. PUA fix to reduce the startup time - https://github.com/open-edge-platform/infra-onboarding/commit/238c2118fcfe126b395cb8c8c271f1004f421937
3. https://github.com/open-edge-platform/edge-node-agents/pull/32
Please describe any newly introduced 3rd party dependencies in this change. List their name, license …
=> PUA fix to reduce the startup time

argocd/applications/configs/infra-managers.yaml
Edge Microvisor Toolkit 3.0.20250605
https://github.com/open-edge-platform/infra-core/pull/236
https://github.com/open-edge-platform/infra-core/pull/245
Pipeline in EMT build system.
=> Use Releases 0.5.3 of OS Profiles with EMT 3.0.20250605 images

argocd/applications/templates/tenancy-api-mapping.yaml, argocd/applications/templates/tenancy-datamodel.yaml
Includes vPro APIs implemented in https://github.com/open-edge-platform/orch-utils/pull/135
N/A
Tested in a deployment by manually using the new chart versions
=> Update tenancy-datamodel and tenancy-api-mapping for vPro

new-installer/targets/aws/iac/acm/acm_test.go
Add missing license header to acm_test.go
N/A
N/A
=> Add missing license file to acm_test.go

argocd/applications/templates/app-deployment-crd.yaml, argocd/applications/templates/app-deployment-manager.yaml
=> Bump App Deployment Manager version

.github/workflows/new-installer-iac-test.yml
=> Fix IAC test CI to check only AWS folder

on-prem-installers/cmd/onprem-ke-installer/main.go
Remove remnants of dead code for LVM based storage class of OpenEBS.
=> Remove unused LVM code

new-installer/internal/steps/onprem/customize_rke2.go, new-installer/targets/onprem/rke2/audit-policy.yaml, new-installer/targets/onprem/rke2/rke2-config.yaml, new-installer/targets/onprem/rke2/rke2-coredns-config.yaml
Adds rancher config to during rke2 install.
N/A
Locally.
=> Add rancher config

new-installer/internal/steps/onprem/customize_rke2.go, new-installer/targets/onprem/rke2/rke2-registries.yaml
Add ability to configure rke2 registries if docker credentials are supplied.
N/A
Locally.
=> Added registries

on-prem-installers/onprem/uninstall_onprem.sh
This reverts commit 7ba13885d2ab677af0daac183b4a660a9f91818e.
The gitea package removal should be added back to the uninstaller.
N/A
Locally.
=> Revert "Remove gitea package from the uninstall script (#434)"

argocd/applications/configs/infra-onboarding.yaml, argocd/applications/templates/infra-core.yaml, argocd/applications/templates/infra-onboarding.yaml
Infra onboarding charts release:  https://github.com/open-edge-platform/infra-charts/pull/90
=> Release infra-onboarding 1.32.1

argocd/applications/templates/edgenode-observability.yaml, argocd/applications/templates/orchestrator-dashboards.yaml, argocd/applications/templates/orchestrator-observability.yaml, argocd/applications/templates/sre-exporter.yaml, e2e-tests/orchestrator/o11y_platform_test.go, tools/resource-limit/manage-resource-limit.py
Bumps versions of o11y charts to newest to reduce security risks.
=> chore: bump o11y versions

pod-configs/orchestrator/cluster/provider.tf
Helm provider for Terraform config is not fixed, and it changes the parameter recently.
This PR includes change to set provider version and use latest format
N/A
CI to verify if it is validate
=> Use Fixed Helm provider version for rel-3.0 branch

.github/CODEOWNERS
=> chore: cleanup and add new codeowners

argocd/applications/configs/infra-onboarding.yaml
Bumping edge node manifest version to latest iteration
Changes:
- https://github.com/open-edge-platform/edge-node-agents/pull/149
- https://github.com/open-edge-platform/edge-node-agents/pull/131
=> Update edge node manifest version to latest

e2e-tests/onboarding/onboarding_test.go
After testing onboarding, also check if the host gets into a running state
N/A
CI
=> Host status check

on-prem-installers/onprem/onprem_upgrade.sh, on-prem-installers/onprem/upgrade_postgres.sh
=> fix postgress sync

argocd/applications/custom/observability-tenant-controller.tpl
Fixes # [ITEP-71731](https://jira.devtools.intel.com/browse/ITEP-71731)
=> fix: set default for sre.enabled to false to avoid rendering as empty

.github/CODEOWNERS
Removed myself from codeowners as I am no longer working on EMF.
=> chore: remove Józef from codeowners

on-prem-installers/onprem/onprem_upgrade.sh
=> added delete platform-keycloak

on-prem-installers/onprem/onprem_upgrade.sh
=> Vault check updated

on-prem-installers/onprem/onprem_upgrade.sh
=> restore old passwords

argocd/applications/templates/app-deployment-crd.yaml, argocd/applications/templates/app-deployment-manager.yaml
Upgrades ADM, fixing two bugs:
1. Parameter templates that are booleans mistakenly applied as strings
2. Fixes and issue in ignoreResources that was caused by a fleet upgrade
=> upgrade app-deployment-manager to 2.4.20

on-prem-installers/onprem/after_upgrade_restart.sh
=> added restart for dependent pod which require restart after 3.0

.github/CODEOWNERS
=> Simplify and update CODEOWNERS

design-proposals/onprem-storage-backup-and-restore.md
This PR adds the storage backup design.
=> Storage backup design

argocd/applications/templates/web-ui-admin.yaml, argocd/applications/templates/web-ui-app-orch.yaml, argocd/applications/templates/web-ui-cluster-orch.yaml, argocd/applications/templates/web-ui-infra.yaml, argocd/applications/templates/web-ui-root.yaml
Releasing UI root version 2.0.18 and related microfrontends. This contains all UI integrations with vPro APIs for 3.1.
=> UI release - 2.0.18

installer/Makefile
=> Fixing make upgrade for public cloud

orch-configs/profiles/profile-oxm.yaml
List microvisor-idv os-profile when deploying oxm profile.
=> Update profile-oxm.yaml to include idv OSprofile

on-prem-installers/onprem/vault_unseal.sh
Check if vault pod exists before checking the status. Timeout if vault pod does not get into a Running state after 5 minutes.
Check if vault keys are retrieved successfully.
Check if vault gets in a ready state.
N/A
=> Fix the vault check pod

argocd/applications/templates/web-ui-infra.yaml
Release of fix for bug: https://jira.devtools.intel.com/browse/ITEP-72966
=> Updated infra version to 1.0.20

argocd/applications/templates/infra-external.yaml
DM manager GRPC service https://github.com/open-edge-platform/infra-external/pull/115
Device reconciler for deactivation https://github.com/open-edge-platform/infra-external/pull/142
=> Infra-external charts release

.github/workflows/virtual-integration.yml, .test-dependencies.yaml, mage/Magefile.go
=> added latest ven tag:pico/1.5.5 for pxe boot

.github/workflows/virtual-integration.yml
=> Unblock onprem VIP by excluding cf7 test due to ITEP-73427 issue

argocd/applications/custom/app-orch-tenant-controller.tpl
=> Bump cluster ext version

argocd/applications/templates/web-ui-admin.yaml, argocd/applications/templates/web-ui-app-orch.yaml, argocd/applications/templates/web-ui-cluster-orch.yaml, argocd/applications/templates/web-ui-infra.yaml, argocd/applications/templates/web-ui-root.yaml
Some important UI bug fixes are going in this release:
https://github.com/open-edge-platform/orch-ui/pull/236
https://github.com/open-edge-platform/orch-ui/pull/237
https://github.com/open-edge-platform/orch-ui/pull/235
https://github.com/open-edge-platform/orch-ui/pull/233
https://github.com/open-edge-platform/orch-ui/pull/226
=> Update UI to 2.0.21

.github/workflows/upgrade.yml
=> chore: set correct permissions

argocd/applications/templates/web-ui-infra.yaml
Release web-ui-infra version 1.0.23 that includes this hotfix - https://github.com/open-edge-platform/orch-ui/pull/241.
=> Update web-ui-infra version to 1.0.23

argocd/applications/configs/infra-external.yaml, argocd/applications/configs/infra-onboarding.yaml, argocd/applications/templates/infra-external.yaml
DM Manager changes
https://github.com/open-edge-platform/infra-external/pull/147/files
https://github.com/open-edge-platform/infra-external/pull/154
Charts changes.
https://github.com/open-edge-platform/infra-charts/pull/123
=> Infra-external 2.7.1 release

.github/actions/cypress/action.yaml, argocd/applications/templates/web-ui-app-orch.yaml, argocd/applications/templates/web-ui-infra.yaml
- Updates deployment-package smoke test with additional tests for import deployment package via helm url and tar file
- Bringing in changes from https://github.com/open-edge-platform/orch-ui/pull/206 into EMF
=> Updated test, app-orch versions

.github/workflows/virtual-integration.yml, argocd/applications/configs/infra-managers.yaml
=> Bump osprofile to 0.7.7 with revert VIP cf7 case exclusion

argocd/applications/templates/web-ui-cluster-orch.yaml
Updated orch-ui cluster-orch version to 2.0.26 from 2.0.25
=> Updated orch-ui CO release version

argocd/applications/templates/infra-external.yaml
Updates infra-external to version 2.7.2. Includes fix for power status when indicator is Unspecified.
=> Infra external release 2.7.2

argocd/applications/templates/infra-core.yaml, argocd/applications/templates/infra-onboarding.yaml
Enforce Tinkerbell pod restart on charts  upgrade
ITEP-74178
#676 
=> Fix Ubuntu upgrade & cve patches for infra

on-prem-installers/onprem/onprem_upgrade.sh
=> Fix upgrade script

argocd/applications/templates/infra-onboarding.yaml
Installer script changes to build and install LMS from the source
OM changes - https://github.com/open-edge-platform/infra-onboarding/pull/238
Charts release - https://github.com/open-edge-platform/infra-charts/pull/134
=> Indra-onboarding chart release 1.33.6

argocd/applications/templates/alerting-monitor.yaml, argocd/applications/templates/auth-service.yaml, argocd/applications/templates/aws-sm-proxy.yaml, argocd/applications/templates/cert-synchronizer.yaml, argocd/applications/templates/edgenode-observability.yaml, argocd/applications/templates/keycloak-tenant-controller.yaml, argocd/applications/templates/observability-tenant-controller.yaml, argocd/applications/templates/orchestrator-observability.yaml, argocd/applications/templates/secrets-config.yaml, argocd/applications/templates/sre-exporter.yaml, argocd/applications/templates/tenancy-api-mapping.yaml, argocd/applications/templates/tenancy-manager.yaml, argocd/applications/templates/token-fs.yaml
Fix CVE-2025-22874 and CVE-2025-47907
=> Use Golang 24.6

pod-configs/module/orch-route53/variable.tf
=> Added ingress route domain to route53

argocd/applications/templates/infra-onboarding.yaml
=> Update infra-onboarding chart version to 1.33.7 for pxe image fix

argocd/applications/templates/web-ui-infra.yaml
Changes Included: 
- https://github.com/open-edge-platform/orch-ui/pull/269
- https://github.com/open-edge-platform/orch-ui/pull/271
=> Update webui-infra version for release 3.1 branch

argocd/applications/templates/web-ui-cluster-orch.yaml
Changes Included:
- https://github.com/open-edge-platform/orch-ui/pull/274
=> Update webui co version to 2.0.30

argocd/applications/configs/infra-managers.yaml
=> OS-Profile update to 0.7.10

pod-configs/utils/provision.sh
Removes hardcoded us-west-2 value from the provisioning script.
N/A
CI
=> remove hardcoded values

argocd/applications/configs/infra-managers.yaml, argocd/applications/templates/infra-core.yaml
Fixes #735 , 76067
Updates OS profile to 0.8.1. EMT images dated Sep 02.
Bump infra-core to 2.17.0 post release
=> Release infra-core 2.17.0 & os-profile 0.8.1

.github/workflows/virtual-integration.yml, .test-dependencies.yaml
This pull request updates the test automation dependency and improves the workflow automation to better respond to changes in test automation configuration. The main changes include updating the version of the test automation tool and enhancing the GitHub Actions workflow to trigger jobs when `.test-dependencies.yaml` is modified.
**Workflow automation improvements:**
* Added a new condition to the `jobs:` section in `.github/workflows/virtual-integration.yml` to detect changes to `.test-dependencies.yaml` and set the `test-automation` flag accordingly.
* Updated job trigger conditions to include the `test-automation` flag, ensuring relevant jobs run when test automation dependencies are changed. [[1]](diffhunk://#diff-c115eba42a2e0ffbf4166b2a198deed597826f1299a9593c50b1bc1edd6e71c6R315) …
=> Update .test-dependencies.yaml to latest version

argocd/applications/configs/infra-managers.yaml
=> Bump os-profile to 0.8.3

pod-configs/utils/provision.sh
=> Cherry-pick "Disable delete protection on traefik3 nlb" into 3.1

README.md
ITEP-77361
This PR adds the orch cli utility as a component in the EMF README file.
=> Adding CLI to README

argocd/applications/configs/kyverno-extra-policies.yaml, argocd/applications/configs/kyverno-traefik-policy.yaml, argocd/applications/configs/kyverno.yaml, argocd/applications/configs/platform-keycloak.yaml, argocd/applications/configs/postgresql.yaml, argocd/applications/configs/secret-wait-tls-boots.yaml, argocd/applications/configs/secret-wait-tls-orch.yaml, argocd/applications/custom/vault.tpl, argocd/applications/templates/app-deployment-manager-secret.yaml, argocd/applications/templates/infra-external.yaml, argocd/applications/templates/keycloak-tenant-controller.yaml, argocd/applications/templates/namespace-label.yaml, argocd/applications/templates/nexus-api-gw.yaml, argocd/applications/templates/secret-wait-azure-ad-creds.yaml, argocd/applications/templates/secret-wait-rs-token.yaml, argocd/applications/templates/secret-wait-tls-boots.yaml, argocd/applications/templates/secret-wait-tls-orch.yaml, argocd/applications/templates/tenancy-api-mapping.yaml, argocd/applications/templates/tenancy-manager.yaml, argocd/applications/templates/wait-istio-job.yaml, bootstrap/gitea.yaml, mage/database.go, mage/keycloak_utils.go, on-prem-installers/assets/gitea/values.yaml, orch-configs/templates/bootstrap/gitea.tpl, pod-configs/module/gitea/gitea-values.yaml.tpl
This PR cherry picks this changes https://github.com/open-edge-platform/edge-manageability-framework/pull/797 into the release-3.1 branch.
n/a
ci
=> Cherry pick "Migrate Bitnami image references to Bitnami Legacy #797" into 3.1

argocd/applications/configs/kyverno.yaml, argocd/applications/configs/secret-wait-tls-boots.yaml, argocd/applications/configs/secret-wait-tls-orch.yaml
This PR updates the kyverno configuration and secret-wait applications. It updates kubectl's image from using bitnamilegacy to alpine.
n/a
ci
=> Update kubectl's image from bitnamilegacy to alpine

.test-dependencies.yaml
This pull request makes a minor update to the `.test-dependencies.yaml` file, upgrading the `test-automation` dependency from version 0.2.4 to 0.2.6.
=> Update test dependency to latest

.test-dependencies.yaml, argocd/applications/custom/app-orch-tenant-controller.tpl
Bump cluster extensions version.
n/a
n/a
=> Bump cluster extensions version in mainline

argocd/applications/templates/app-deployment-crd.yaml, argocd/applications/templates/app-deployment-manager.yaml
Updated ADM and CRD to 2.5.2, Contain the fix for filtering failing with Deployment Metadata
=> Bump ADM version to 2.5.2

.github/workflows/virtual-integration.yml, .tool-versions
Fixed the yamllint error: 
ModuleNotFoundError: No module named 'yaml'
Error: running "yamllint -c tools/yamllint-conf.yaml argocd/applications/configs" failed with exit code 1
Error: Process completed with exit code 1.
=> Fix the yamllint issue

.test-dependencies.yaml, argocd/applications/custom/app-orch-tenant-controller.tpl
cherry picking the cluster extension changes from https://github.com/open-edge-platform/cluster-extensions/pull/138
=> chore: Bump cluster extension version for 3.1.3 release

argocd/applications/templates/cert-manager.yaml, argocd/applications/templates/nginx-ingress-pxe-boots.yaml
Jira: https://jira.devtools.intel.com/browse/ITEP-68866
=> updated cert manger to latest version and cert size reduced RSA4096 to RSA3072 

argocd/applications/templates/infra-core.yaml
Fixes # 76067
- https://github.com/open-edge-platform/infra-core/pull/518
- https://github.com/open-edge-platform/infra-charts/pull/151
=> Bump infra-core to fix multi-tenant user access

argocd/applications/templates/web-ui-cluster-orch.yaml, argocd/applications/templates/web-ui-infra.yaml
Includes this cherry-picked nokia issue PR in release-3.1 branch - https://github.com/open-edge-platform/orch-ui/pull/322
=> update web-ui-infra to 1.0.32

argocd/applications/custom/app-orch-tenant-controller.tpl
update cluster ext verison includes fix for usb redeployemnt failure occuring due to bitnami images
=> chore: Bump cluster ext to 1.3.14

argocd/applications/templates/web-ui-admin.yaml, argocd/applications/templates/web-ui-app-orch.yaml, argocd/applications/templates/web-ui-cluster-orch.yaml, argocd/applications/templates/web-ui-infra.yaml, argocd/applications/templates/web-ui-root.yaml
Update all UI versions to 3.2 for further dev. This PR includes these changes as well: 
- https://github.com/open-edge-platform/orch-ui/pull/320
- https://github.com/open-edge-platform/orch-ui/pull/325
=> Update UI versions to 3.2
