open-edge-platform/edge-manageability-framework

e2e-tests/orchestrator/o11y_alerts_test.go

This PR stabilizes o11y alert tests by temporarily disabling the test `verify that email notifications are being sent` that has been reported to fail intermittently in CI.
None.
This change was tested by running end-to-end tests.

Temporarily disable flaky o11y alert notifications test.

---

pod-configs/orchestrator/cluster/main.tf

User should provide full email when email notification is enabled.
We have this setting in the document:
https://github.com/open-edge-platform/orch-docs/blob/main/docs/shared/shared_adv_alerts.rst
No
To be tested with integration pipeline

Remove intel.com email from Terraform config

---

on-prem-installers/mage/Magefile.go
terraform/orchestrator/terraform.tfvars
terraform/orchestrator/variables.tf

- Keep artifact tags consistent for on-prem installers and repo archives
- Revert #222 to use `latest-main-dev` as default tag for onprem deploy function

Fix on-prem artifact tag discrepancy 

---

mage/deploy.go

When deploying kind cluster on a EC2 instance with IMDSv2 enabled, we need to obtain the token first before using metadata service.
N/A
Tested with mage deploy command

Support using IMDSv2 to get availability zone

---

buildall/Makefile
buildall/README.md
buildall/env.sh
buildall/scripts/buildall.sh
buildall/scripts/helm_build.sh
buildall/scripts/image_build.sh
buildall/scripts/sort_charts.py
buildall/scripts/sort_images.py

Reduce verbosity of buildall process, while retaining debuggability.
List external requirements, from individual repos that are built. 
Run manually, which is enough for buildall.

Chore: Reduce verbosity of buildall

---

.github/workflows/virtual-integration.yml

Downsizes the CI runner for the On-Prem job from `ubuntu-22.04-32core-128GB` to `ubuntu-24.04-16core-64GB` to reduce 💵

Downsize On-Prem CI runner to reduce costs

---

argocd/applications/templates/app-deployment-crd.yaml
argocd/applications/templates/app-deployment-manager.yaml
argocd/applications/templates/app-orch-catalog.yaml
argocd/applications/templates/app-orch-tenant-controller.yaml
argocd/applications/templates/fleet-controller.yaml
argocd/applications/templates/fleet-crd.yaml
mage/edge_cluster.go

This PR upgrades Fleet to version 0.12.2 and ADM to version 2.4.7, which uses the new Fleet API accordingly. (https://github.com/open-edge-platform/app-orch-deployment/pull/62) 
This PR also upgrades app-orch-tenant-controller to version 0.3.2
This PR also upgrades app-orch-catalog to version 0.14.1
No new dependencies. Fleet is upgraded to 0.12.2 
This change was tested using EnIC and ADM component tests. Additionally, it was tested using a stress test to verify that extensions can be deployed without any problems.

Upgrade fleet to 0.12.2

---

design-proposals/app-orch-helm-to-dp.md

This is a design proposal for accepting an OCI URL from the user and using it to import a Helm Chart from the user, verifying the validity of that chart, and then creating a deployment package in the orchestrator.

Design proposal for importing Helm Charts to automatically create Deployment Packages

---

e2e-tests/orchestrator/orchestrator_test.go
mage/deploy.go

Increase timeout to allow for setting up service component during e2e tests.
N/A
On CI

Increase timeout during e2e to allow for service component creation

---

argocd/applications/custom/app-orch-tenant-controller.tpl
argocd/applications/templates/app-orch-tenant-controller.yaml

Updates manifest to use a new version of kubevirt-helper that does not use edge node release proxy. Updates app-orch-tenant-controller with additional validations.
Tested deployment of virtualization extension. App-orch-tenant controller was a validation, unit testing, and fuzz testing update, and does not affect runtime behavior.

update tenant-controller to 0.3.5 and manifest to 1.1.2

---

design-proposals/cluster-orch-integrating-k8s-into-emt.md

Update implementation and test plan for Integration of K3s into EMT and also updates to k8s install work flow.
None
NA

Update implementation and test plan

---

.github/CODEOWNERS
argocd/applications/templates/app-orch-tenant-controller.yaml
argocd/applications/templates/app-service-proxy.yaml
e2e-tests/orchestrator/catalog_bootstrap_test.go

Bump Tenant Controller to 0.3.8
* This add support for upgrade of cluster extensions ([link](https://github.com/open-edge-platform/app-orch-tenant-controller/pull/17))
* Sets the rootUrl of the harbor-oci-registry to include the harbor project name ([link1](https://github.com/open-edge-platform/app-orch-tenant-controller/pull/36), [link2](https://github.com/open-edge-platform/app-orch-tenant-controller/pull/37))
Bump App Service Proxy to 1.4.3
* Fixes a problem with Cross-Origin-Embedder-Policy on proxied applications ([link](https://github.com/open-edge-platform/app-orch-deployment/pull/88))
Fixes # ITEP-67065, ITEP-21737
None
Ran on coder and local tests

ITEP-67065 bump Tenant Controller and ASP

---

argocd/applications/templates/tenancy-api-mapping.yaml

Use tenancy-api-mapping chart 0.5.0 (container 1.4.0), per updates in https://github.com/open-edge-platform/orch-utils/pull/100
Fixes # various
None 
Build/run of container locally

Update tenancy-api-mapping to 0.5.0

---

.github/workflows/auto-update.yml

chore: switch to self hosted update action

---

.github/workflows/virtual-integration.yml

Exclude installer from Kind VIP / On-Prem VIP for now.
We can later reintroduce it back to On-Prem VIP
N/A
N/A

chore: only run deploy-kind / deploy-onprem when change does not include new-installer

---

argocd/applications/custom/app-orch-catalog.tpl
argocd/applications/templates/app-deployment-manager.yaml
argocd/applications/templates/app-orch-catalog.yaml

Updates app-orch-catalog to 0.14.2 and sets the proxy settings to be used inside the container. Prerequisite for catalog import feature. Also, bump ADM to l2.4.12 to pull in fix for flipping state.
No
Tested in Coder.

add proxy settings to app-orch-catalog

---

.github/CODEOWNERS

Workaround as described in https://github.com/orgs/community/discussions/23064#discussioncomment-8383923 to allow Dependabot PRs to be auto-merged without CODEOWNER review.

Remove CODEOWNER enforcement on dependency files

---

new-installer/cmd/config/validate.go
new-installer/cmd/config/validate_test.go

fix(config): support single hostname, with or without leading dot (localhost, .svc) in no proxy
N/A
Unit test

fix(config): support single hostname, with or without leading dot (localhost, .svc) in no proxy

---

argocd/applications/templates/app-orch-catalog.yaml
argocd/applications/templates/nexus-api-gw.yaml

Updates to the latest app-orch-catalog and nexus-api-gw component versions. This includes a change to support passing the Content-Type and Content-Disposition headers through nexus-api-gw in support of the new Catalog API for downloading deployment packages.
No.
Tested in Coder and tested with Catalog Component Tests.

update app-orch-catalog and nexus-api-gw for download API

---

on-prem-installers/mage/upgrade.go

v3.0.0 uses v1.30.10+rke2r1. Further versions of this repo will use this rke2 version as a starting point. We don't need to upgrade from an earlier version. 
N/A
Locally.

Remove support for older rke2 versions

---

argocd/applications/templates/app-deployment-manager.yaml

Updates app-deployment-manager to 2.4.27. Includes the following:
* Fixes issue with DeleteSecrets failing when secrets are not found (may address github issue #644)
* Updates to Go version 1.24.6
* Removes unused AWS library
* Removes Codecommit support
No.
Tested using ADM component tests and manual coder deployment.

update app-orch-deployment to 2.4.27

---

.test-dependencies.yaml
argocd/applications/custom/app-orch-tenant-controller.tpl

Updates cluster extensions to pull in a new kubernetes-dashboard extension that disables open ports in the kong-proxy admin and api.

update cluster-extensions to close kong-admin port

---

.github/workflows/virtual-integration.yml

This pull request updates the workflow logic in `.github/workflows/virtual-integration.yml` to improve how changed files are processed for the "only design proposals" check. The most important change is a more robust method for cleaning and splitting the list of changed files before evaluating them.
Workflow logic improvements:
* Improved parsing of the `changed_files` output by removing brackets and quotes and trimming whitespace from each filename to ensure accurate file matching. (`.github/workflows/virtual-integration.yml`)
* Added an explicit debug output line to print the value of `only_design` for easier troubleshooting. (`.github/workflows/virtual-integration.yml`)
Please describe any newly introduced 3rd party dependencies in this change. List their name, license …

Fix skip kind and onprem VIP jobs if only design proposal changes

---

pod-configs/utils/provision.sh

Delete protection should be disabled on the newly added nlb when running destroy. 
If this is not disabled, the uninstall fails to destroy this resource. 
n/a
Manual check.

Disable delete protection on traefik3 nlb

---

argocd/applications/configs/kyverno.yaml

This PR changes kyverno kubectl images used in the cleanup controllers from bitnamilegacy to eclipsefdn
n/a
ci.

Migrate kyverno kubectl images used in the cleanup controllers from bitnamilegacy to eclipsefdn

---

argocd/applications/configs/platform-keycloak.yaml

This PR migrates keycloakConfigCli  from bitnami to bitnamilegacy.
N/A
ci/locally

Migrate keycloakConfigCli from bitnami to bitnamilegacy
